### ISSUE TITLE
plank-config.vala:102 config file could not be found

### ISSUE THREAD

**Issue by maxiride** [eericart/Plank-Config#5]
Hello, I recently installed Plank on an Arch linux system using the provided package in the community repo.

When launching plank-config from the terminal I get this error:

```
[federico@arch-anywhere-federico]: ~>$ plank-config 

** (plank-config:19588): ERROR **: plank-config.vala:102: Plank config file could not be found!
Rilevato trace/breakpoint (core dump creato)
[federico@arch-anywhere-federico]: ~>$ 

```

Plank on the other hand is installed and running smoothly. Is it an error related to the software itself or should I contact the package creator on the Arch repo?

**Comment by funkyfuture** [comment]
nah, the packager shouldn't put empty config files in a user's directory. `plank-config` should create an empty one in this case.

**Comment by ghost** [comment]
@funkyfuture: so what is the workaround?

UPDATE1: answering my own question: `touch ~/.config/plank/dock1/settings`

UPDATE2: update #1 is irrelevant, since `plank-config` is outdated so needs to be removed anyway. Configuring the current version of `plank` is done by holding CTR+right-click on the dock. Duh.. Why did I need to google for it?..
